version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/repo
    environment:
      GOOROT: /home/ubuntu/.gimme/versions/go1.8.linux.amd64
      NODE_VERSION: 7.7.4

jobs:
  dependencies:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./infrastructure/scripts/dependencies
      - save_cache:
          key: dependency-cache-{{ checksum "infrastructure/scripts/dependencies" }}
          paths:
            - /home/ubuntu/.go_workspace
            - /home/ubuntu/.gimme
            - /home/ubuntu/.npm
            - /home/ubuntu/libsysconfcpus
            - /home/ubuntu/sysconfcpus
            - /home/ubuntu/snaas/cmd/console/tests/elm-stuff
      - run:
          name: Clear Git Config
          command: echo "" > ~/.gitconfig

  database:
    executor: default
    steps:
      - checkout
      - run:
          name: Setup Database
          command: PGPASSWORD=unicode psql -U ubuntu -d circle_test -f platform/pg/setup.sql -h 127.0.0.1

  test:
    executor: default
    steps:
      - checkout
      - run:
          name: Execute Go Tests
          command: ./infrastructure/scripts/execute-go-tests
      # Uncomment the following line if you need to run Elm tests
      # - run:
      #     name: Execute Elm Tests
      #     command: ./infrastructure/scripts/execute-elm-tests

  build_and_deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Container
          command: ./build
      - run:
          name: Login to DockerHub
          command: docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
      - run:
          name: Push Docker Image
          command: docker push tapglue/snaas

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - database:
          requires:
            - dependencies
      - test:
          requires:
            - database
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only: master
