machine:
  environment:
    GOOROT: /home/ubuntu/.gimme/versions/go1.8.linux.amd64
  node:
    version: 7.7.4
  services:
    - docker
    - postgresql
    - redis
dependencies:
  cache_directories:
    - "/home/ubuntu/.go_workspace"
    - "/home/ubuntu/.gimme"
    - "/home/ubuntu/.npm"
    - "/home/ubuntu/libsysconfcpus"
    - "/home/ubuntu/sysconfcpus"
    - "/home/ubuntu/snaas/cmd/console/tests/elm-stuff"
  override:
    - ./infrastructure/scripts/dependencies
  pre:
    - echo "" > ~/.gitconfig
database:
  override:
    - PGPASSWORD=unicode psql -U ubuntu -d circle_test -f platform/pg/setup.sql -h 127.0.0.1
test:
  override:
    - ./infrastructure/scripts/execute-go-tests
    # - ./infrastructure/scripts/execute-elm-tests
deployment:
  docker:
    branch: master
    commands:
      - ./infrastructure/scripts/build-container
      - docker login -e ${DOCKERHUB_EMAIL} -p ${DOCKERHUB_PASSWORD} -u ${DOCKERHUB_USERNAME}
      - docker push tapglue/snaas